default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER", "postgresql") %>
  pool: <%= ENV.fetch("DATABASE_POOL", 5) %>
  timeout: <%= ENV.fetch("DATABASE_TIMEOUT", 5000) %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  database: <%= ENV["DATABASE_NAME"] %>

development:
  <<: *default

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
